version: "3.9"

services:
  llm_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llm_deploy_container
    working_dir: /app/deploy
    command: bash -c "./start_server.sh & ./start_tunnel.sh && tail -f /dev/null"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always
